package org.test.tamplets;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.DateField;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextArea;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SignUpPanel extends HorizontalLayout {
    protected TextField nameTextField;
    protected TextField surnameTextField;
    protected TextField emailTextFeild;
    protected DateField birthDateField;
    protected PasswordField passwordTextField;
    protected PasswordField repeatPasswordTextField;
    protected TextArea educationTextArea;
    protected Button signUpButton;

    public SignUpPanel() {
        Design.read(this);
    }
}
