package org.test.tamplets.menupage.profilepage.inboxpage;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.RichTextArea;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class InboxComposePanel extends VerticalLayout {
    protected TextField receiverEmailTextField;
    protected TextField themeTextField;
    protected RichTextArea richTextArea;
    protected Button sendMessageButton;

    public InboxComposePanel() {
        Design.read(this);
    }

    public TextField getReceiverEmailTextField() {
        return receiverEmailTextField;
    }

    public TextField getThemeTextField() {
        return themeTextField;
    }

    public RichTextArea getRichTextArea() {
        return richTextArea;
    }

    public Button getSendMessageButton() {
        return sendMessageButton;
    }
}
