package org.test.tamplets.menupage.profilepage.inboxpage;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.Label;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class InboxReadPanel extends VerticalLayout {
    protected Label dateLabel;
    protected Label senderNameLabel;
    protected Label senderEmailLabel;
    protected Label receiverNameLabel;
    protected Label receiverEmailLabel;
    protected Label themeLabel;
    protected RichTextArea richTextArea;

    public InboxReadPanel() {
        Design.read(this);
    }
}
